### PR TITLE
fix to make qBall work with fw1 right out the box

### PR DESCRIPTION
**Pull request by chanhong**
add MyApplication.cfc so that it can be set up to work with fw1 right out of the box.

### CODE REVIEW

**Comment by seancorfield** [comment]
Given that you've split `Application.cfc` in two, I can't see what actual changes you made to fix the problem. Closing this. Feel free to send a PR for the _minimal_ change that would fix the problem.

**Comment by chanhong** [comment]
The reason for the change was the code does not work as is because the "framework" folder was not in the "gBall" folder and if it does not have a mapped in the administration whereas this change will have the needed map of "framework" in the code so it will work with the code that pulls down from Github.

**Comment by seancorfield** [comment]
The README says the whole repo is intended to be checked out as a complete web application so `framework` is in the webroot and `/framework`  "Just Works". That's how all the examples work by default. Only some of them have been updated to use the **Alternative Application Structure** because not everyone is going to want to use that approach in their applications.

**Comment by seancorfield** [comment]
If you use CommandBox -- highly recommended! -- then you can just check out the whole repo, `cd` into it, and run `box start` and all the examples work (because the repo is the websoot).

**Comment by seancorfield** [comment]
(which is why Getting Started _begins_ with using CommandBox to install FW/1 because then all of this "Just Works" -- and I also recommend you read https://github.com/framework-one/fw1-commands )

**Comment by chanhong** [comment]
I do use command box and I do use fw1-commands and now I can see your reason for doing what you did.  Thanks for taking the time to explain.

**Comment by seancorfield** [comment]
👍

**Pull request closed without merging**
