### PR TITLE
Wiring under load

### PR DESCRIPTION
**Pull request by aliaspooryorik**
jMeter load Test for a issue which has been seen under heavy load where a transient which has a dependency on a singleton, doesn't always get wired up.

At first I added the lock where the comments were in the code (changing the syntax of the comments slightly so Lucee doesn't think it's metadata!) but still get occasional errors around 0.1% failure. Extended the lock which seems to do the trick but would be interesting to test on faster hardware as my laptop is quite old.

To run this test you will need to use jMeter (and optional commandbox).

The jMeter test expects the server to accessible at localhost:8765 but you change
port and hostname in the test. The expected response is 'Hello World'

DI/1 is reloaded in the the test applications application scope on each test run.

Hope this is helpful.

### CODE REVIEW

**Comment by jcberquist** [comment]
I am interested in the behavior of transients under load, so I took a look at this. It does seem that adding the lock stops the failures; at least I can't get errors on my hardware with the lock in place. 

I think I might know what is going on, and I am not sure if the lock fixes the issue, or just makes it very unlikely. This is what I think might be happening:

Properties are injected in the `resolveBean()` method (at [Line 766](https://github.com/framework-one/fw1/blob/develop/framework/ioc.cfc#L766)). This is done by looping through the `partialBean.injection` struct and evaluating `injection.bean.set#property#(...)` for each property where a bean name is known (where `injection` is equivalent to `partialBean.injection[beanName]`). What `resolveBean()` returns is `partialBean.bean` - `partialBean.bean.set#property#` is not evaluated. For a singleton, `partialBean.bean` and `injection.bean` are (in theory) references to the same instance, so this is not an issue.  In order to ensure this with transients, which are created anew each time, we have [lines 896-898](https://github.com/framework-one/fw1/blob/develop/framework/ioc.cfc#L896-L898) . But the `partialBean.injection` struct is ultimately contained in the `variables` scope of `ioc.cfc`. So, under load, it is possible for the transient instance in the injection struct to end up being a different instance than `partialBean.bean` (i.e. after another thread has reached lines 896-898), and hence the setter on that particular transient `partialBean.bean` will never get called.

**Comment by seancorfield** [comment]
Ugh! Yes, this is the fallout from an optimization I made a while back, trying to cache the accumulator (which is fine for singletons) to prevent a whole bunch of scanning of the dependency tree on subsequent requests. It just isn't safe for transients.

**Comment by seancorfield** [comment]
This is the where the problem was introduced (in 4.0): https://github.com/framework-one/fw1/issues/409

**Comment by jcberquist** [comment]
Some more history: #420 is the source of lines 896-898, which was implemented to ensure `accumulator.bean` and `accumulator.injection[beanName].bean` were references to the same bean in the case of transients. That left the problem that the `accumulator` struct was in the variables scope, which was the source of issue https://github.com/framework-one/fw1/issues/449. After the fix for that, we have the current situation, where the setters are called on the `accumulator.injection` instance of the transient, which is still in the `variables` scope, but the transient bean returned does not come from the `variables` scope.

I would like to suggest a fix where the `accumulator` struct that is passed from `resolveBean()` to `resolveBeanCreate()` is not cached in the `variables` scope, while we still cache injection singletons:

https://gist.github.com/jcberquist/51919c7b6fd4c4d264c218275a06464c

Modifying `resolveBean()` in this way does resolve the issue @aliaspooryorik is seeing - his jMeter load test passes with it in place. I welcome further review of it, of course. Assuming this is a viable approach, it is going to add some overhead to the `resolveBean()` method, but does have the benefit of keeping transients out of the `variables` scope, even when they are in the `accumulator.injection` struct. If you went this route, it might be possible to to revert the fix for #449 (if desired), and I also think it would make the fix for #420 no longer necessary.

**Comment by aliaspooryorik** [comment]
Just tested @jcberquist 's fix on Lucee 4.5 and ACF 2016 and looks solid :+1: Nice work.

**Comment by seancorfield** [comment]
@jcberquist Can you go ahead and submit a PR against **develop** containing your proposed changes? It looks like the right approach -- caching just the dependencies and not the injections themselves for transients. Thank you!

I'm closing this as no longer appropriate (but thanks for leading the initial investigation @aliaspooryorik ).

**Comment by seancorfield** [comment]
(and include the reversion of those other fixes as appropriate please)

**Comment by seancorfield** [comment]
Given this is a thread safety issue, I may backport it to **master** and cut 4.0.1 with this fix. Thoughts?

**Comment by jcberquist** [comment]
@seancorfield: Sorry for the delayed response, I have been a bit busy. I will try to get a PR together in the next couple of days.

**Pull request closed without merging**
