### PR TITLE
For #325 add placeholder specific regex syntax for routes

### PR DESCRIPTION
**Pull request by guillaume-boivin**
> I definitely think we wouldn't want to repeat the regex in the target route so {id:[0-9]+} in the route would match :id in the target so if you can add that in

Done

### CODE REVIEW

**Comment by seancorfield** [comment]
:+1:

**Comment by seancorfield** [comment]
Fixes #325

**Comment by seancorfield** [comment]
I was a bit puzzled that the expected result string ended in `/` - seems like `name=computer/` would make `/` part of the value passed as the `name` parameter. Is that just a weird artifact of how the test is set up?

**Comment by guillaume-boivin** [comment]
Good point, in the code it seems that we take for granted that the target route will be used with the `/param1/param1value/param2/param2value/`. 

This code (https://github.com/framework-one/fw1/blob/master/framework/one.cfc#L1752) adds the `/` part at the end. 

I'm going to tinker a bit more about this and send a fix for it when I have the time. Let's says that for now the placeholder specific syntax works only with the forward slash syntax.

**Comment by seancorfield** [comment]
Yes, I think I've always worked under the assumption that routes map from one set of SES URLs to another set of SES URLs but I'm not sure that's written into the docs (and it should be). Thanks for the sanity check there. I think we'll leave it as it is and just make sure that's documented.

**Comment by seancorfield** [comment]
It looks like this was never documented in 3.1, so I'm adding it to the 3.5 documentation and will try to remember to back-port it after I make the release final (so I only have to update the 3.1 files, not the current stable files as well!).

**Pull request merged**
