### PR TITLE
Fix for issue #452

### PR DESCRIPTION
**Pull request by cfchef**
Removes the trailing "/" that may be included in `framework.baseURL` - Example: `http://" & cgi.HTTP_HOST & "/myapp/`.

Tested URLs to build:
```
buildURL( 'product.list' )
buildURL( action = 'product.detail', queryString = 'id=42?img=large##overview' )
buildURL( 'product.detail?id=42?img=large##overview' )
buildURL( '.list' )
```

### CODE REVIEW

**Comment by cfchef** [comment]
I made a amateur mistake and didn't consider a baseURL without the "/". Gonna need to make a tweak.

**Comment by seancorfield** [comment]
Why not just remove any trailing / at the point where baseURL is setup? A small, localized change that addresses just the original problem.

**Comment by cfchef** [comment]
Didn't think about that. I'll look into it when I have some free time.

**Comment by dnando** [comment]
I'm using baseURL = '/' on production. Would be really helpful to me if
that wasn't broken by this change.



Aria Media Sagl
+41 (0)76 303 4477 cell
skype: ariamedia

**Comment by cfchef** [comment]
@dnando are you using `generateSES` set to `false` with `baseURL` being "/"?

I was looking at handling the "/" in resolveBaseURL and with SES set to true that's yielding a "//" so I'll have to look into that along with allowing just "/".

It could be something simple, I just haven't had the time to do much digging at the moment. Def not trying to break anything that's working properly if it has a use.

**Comment by seancorfield** [comment]
The simplest solution here: in the code that sets up the framework defaults, if len(baseURL) > 1 and baseURL endsWith /, remove that final character. That will preserve baseURL == "/" and fix the other case.

**Comment by cfchef** [comment]
@seancorfield,

Thanks for the followup. That was generally where I was going with it. I didn't think to apply it where you've suggested though.

I've applied my change. If that seems appropriate, it looks like that one test needs to be updated to expect it without the "/". I can make that change.

Something I noticed, and this might just be an outcome of the usage mixed with the settings (whether acceptable or wrong), is when you set baseURL to "/" and have generateSES set to true, you end up getting a leading "//". I personally don't use that setup so I have no experience either way as to whether that usage is worth worrying about.

I'm here to take feedback and help. Cheers.

**Comment by seancorfield** [comment]
Cool, yeah, looks like one test needs updating to account for the removal of the trailing /

As for generateSES and baseURL = /, I think that's an edge case so unless someone complains that is causing problems, I wouldn't worry about that. Either it works for Nando as-is or he's not generating SES URLs, and in both cases it's fine :)

If someone later complains that really is broken, I guess extending this change to "fix" baseURL if generateSES is true is the smallest fix :)

**Comment by cfchef** [comment]
I figured. Thanks Sean.

**Comment by seancorfield** [comment]
👍

**Pull request merged**
